"""addde_buddies_counts

Revision ID: 6e7851e41d90
Revises: c68fddb6c077
Create Date: 2026-02-28 06:32:43.898584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e7851e41d90'
down_revision: Union[str, Sequence[str], None] = 'c68fddb6c077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('events_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('buddies_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'buddies_count')
    op.drop_column('users', 'events_count')
    # ### end Alembic commands ###
